Likhtarovich_90311/Controllers/AnimalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Likhtarovich_90311.DAL.Data;
using Likhtarovich_90311.DAL.Entities;
using Likhtarovich_90311.Extensions;
using Likhtarovich_90311.Models;

namespace Likhtarovich_90311.Controllers
{
    public class AnimalController : Controller
    {
        //public List<Animal> _animals;  //паблик для теста
        //List<AnimalGroup> _animalGroups;
        ApplicationDbContext _context;
        int _pageSize;
        private ILogger _logger;

        public AnimalController(ApplicationDbContext context, ILogger<AnimalController> logger)
        {
            _pageSize = 3;
            //SetupData();
            _context = context;
            _logger = logger;
        }

        [Route("Catalog")]
        [Route("Catalog/Page_{pageNo}")]       
        public IActionResult Index(int? group, int pageNo=1)
        {
            var groupName = group.HasValue
                ? _context.AnimalGroups.Find(group.Value)?.GroupName
                : "all groups";

            _logger.LogInformation($"info: group={group}, page={pageNo}");

            var animalsFiltered = _context.Animals.Where(d => !group.HasValue || d.AnimalGroupId == group.Value);
            // Поместить список групп во ViewData
            ViewData["Groups"] = _context.AnimalGroups;
            // Получить id текущей группы и поместить в TempData
            ViewData["CurrentGroup"] = group ?? 0;

            //return View(ListViewModel<Animal>.GetModel(animalsFiltered, pageNo, _pageSize));

            var model = ListViewModel<Animal>.GetModel(animalsFiltered, pageNo, _pageSize);
            //if (Request.Headers["x-requested-with"]
            //.ToString().ToLower().Equals("xmlhttprequest"))
            //    return PartialView("_listpartial", model);

            if (Request.IsAjaxRequest())
                return PartialView("_listpartial", model);

            else
                return View(model);
        }

        /// <summary>
        /// Инициализация списков
        /// </summary>
        //private void SetupData()
        //{
        //    _animalGroups = new List<AnimalGroup>
        //    {
        //        new AnimalGroup {AnimalGroupId=1, GroupName="Попугаи"},
        //        new AnimalGroup {AnimalGroupId=2, GroupName="Приматы"},
        //        new AnimalGroup {AnimalGroupId=3, GroupName="Змеи"},
        //        new AnimalGroup {AnimalGroupId=4, GroupName="Грызуны"},
        //        new AnimalGroup {AnimalGroupId=5, GroupName="Кошки"}                
        //    };
        //    _animals = new List<Animal>
        //    {
        //        new Animal {AnimalId = 1, AnimalName="Попугай Ара", 
        //            Description="Крупные попугаи с очень яркой окраской зелёных, " +
        //            "красных, голубых и жёлтых тонов ",
        //            Age =50, AnimalGroupId=1, Image="Ara.jpg" },
        //        new Animal {AnimalId = 2, AnimalName="Попугай корелла",
        //            Description="Средних размеров попугай, почти половину длины тела составляет длина хвоста." +
        //            "Вес тела от 80 до 150 грамм.",
        //            Age =15, AnimalGroupId=1, Image="Corella.jpg" },

        //        new Animal { AnimalId = 3, AnimalName="Мартышка", 
        //            Description="Довольно небольшие обезьяны. Длина тела составляет от 30 до 100 сантиметров.",
        //            Age =10, AnimalGroupId=2, Image="Martishka.jpg" },
        //        new Animal { AnimalId = 4, AnimalName="Шимпанзе",
        //            Description="Род обезьян из семейства гоминидов.",
        //            Age =35, AnimalGroupId=2, Image="Shimpanze.jpg" },
        //        new Animal { AnimalId = 5, AnimalName="Павиан",
        //            Description="Эти обезьяны отличаются высокой агрессивностью, но при этом умело уживаются с людьми.",
        //            Age =15, AnimalGroupId=2, Image="Pavian.jpg" },

        //        new Animal { AnimalId = 6, AnimalName="Коралловый аспид",
        //            Description="Род ядовитых змей из семейства аспидов (Elapidae). Имеют яркую окраску с " +
        //            "характерными чёрными, красными и жёлтыми кольцами",
        //            Age =3, AnimalGroupId=3, Image="Aspid.jpg" },
        //        new Animal { AnimalId = 7, AnimalName="Черная мамба",
        //            Description="Ядовитая змея, распространённая в Африке. Длина тела может превышать 3 м",
        //            Age =5, AnimalGroupId=3, Image="Mamba.jpg" },
        //        new Animal { AnimalId = 8, AnimalName="Тигровый питон",
        //            Description="Крупная неядовитая змея. Длина тела может варьироваться от 1,5 до 4 м и более, в зависимости от пола",
        //            Age =15, AnimalGroupId=3, Image="Piton.jpg" },

        //        new Animal {AnimalId = 9, AnimalName="Сурок",
        //            Description="Крупные, весом в несколько килограммов, животные, обитающие в открытых " +
        //            "ландшафтах, в сооружаемых самостоятельно норах." ,
        //            Age =2, AnimalGroupId=4, Image="Surok.jpg" },
        //        new Animal {AnimalId = 10, AnimalName="Хомяк",
        //            Description="Размеры хомячков могут варьироваться от 5 до 37 см," +
        //            " а вес — от 45 до 700 граммов.",
        //            Age =1, AnimalGroupId=4, Image="Homyak.jpg" },

        //        new Animal { AnimalId = 11, AnimalName="Бенгальская кошка",
        //            Description="Межродовой гибрид домашней кошки и бенгальской кошки ",
        //            Age =7, AnimalGroupId=5, Image="Koshka.jpg" }
        //    };
        }
    
}

Likhtarovich_90311/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Likhtarovich_90311.DAL.Data;
using Likhtarovich_90311.Extensions;
using Likhtarovich_90311.Models;

namespace Likhtarovich_90311.Controllers
{
    public class CartController : Controller
    {
        private ApplicationDbContext _context;
        private string cartKey = "cart";
        private Cart _cart;

        public CartController(ApplicationDbContext context, Cart cart)
        {
            _context = context;
            _cart = cart;
        }

        public IActionResult Index()
        {
            //_cart = HttpContext.Session.Get<Cart>(cartKey);
            return View(_cart.Items.Values);
        }

        [Authorize]
        public IActionResult Add(int id, string returnUrl)
        {
            //_cart = HttpContext.Session.Get<Cart>(cartKey);
            var item = _context.Animals.Find(id);
            if (item != null)
            {
                _cart.AddToCart(item);
                //HttpContext.Session.Set<Cart>(cartKey, _cart);
            }
            return Redirect(returnUrl);
        }

        public IActionResult Delete(int id)
        {
            _cart.RemoveFromCart(id);
            return RedirectToAction("Index");
        }
    }
}

Likhtarovich_90311/Views/Animal/Index.cshtml
@model ListViewModel<Animal>

@{
    ViewData["Title"] = "Меню";

var categories = ViewData["Groups"] as IEnumerable<AnimalGroup>;
int currentGroup = (int)ViewData["CurrentGroup"];
var text = currentGroup !=0
? categories
.FirstOrDefault(g => g.AnimalGroupId == currentGroup)?
.GroupName
: "Все";
}

<div class="row">
    <div class="col-2">
        <div class="dropdown mt-2">
            <a class="btn btn-secondary dropdown-toggle"
               asp-action="Index" asp-controller="Animal"
               role="button"
               id="dropdownMenuLink"
               data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
                @text
            </a>
            <div class="dropdown-menu"
                 aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item"
                   asp-action="Index"
                   asp-controller="Animal">Все</a>
                @foreach (var item in categories)
{
                <a class="dropdown-item"
                   asp-action="Index"
                   asp-controller="Animal"
                   asp-route-group="@item.AnimalGroupId"
                   asp-route-pageNo="1">@item.GroupName</a>
}
            </div>
        </div>
    </div>
    <div class="col-10">

        @*<div class="card-deck">
            @foreach (var item in Model)
            {
                <partial name="_ListItemPartial" model="@item" />
            }
        </div>*@

        <div class="card-group" id="list">
            <partial name="_ListPartial" model="@Model" />
        </div>

        <pager page-current="@Model.CurrentPage"
               page-total="@Model.TotalPages"
               action="Index"
               controller="Animal"
               group-id="@currentGroup"></pager>
    </div>

Likhtarovich_90311/Views/Animal/_ListItemPartial.cshtml
@model Animal

<div class='card m-2 p-1 text-center col-4'>
    <img src="~/Images/@Model.Image"
         alt='NoImage'
         class="card-img-top" />
    <div class="card-body">
        <h5 class="card-title">
            @Model.AnimalName
        </h5>
        <p class="card-text">
            @Model.Description
        </p>
        <div class="card-text badge badge-secondary">
            <h6>Возраст @Model.Age лет</h6>
        </div>
        @{ // Получение текущего адреса
            var request = ViewContext.HttpContext.Request;
            var returnUrl = request.Path +
            request.QueryString.ToUriComponent();
        }
        <!--Разметка кнопки добавления в корзину-->
        <p class="mt-2">
            <a asp-action="Add"
               asp-controller="Cart"
               asp-route-id="@Model.AnimalId"
               asp-route-returnUrl="@returnUrl"
               class="btn btn-primary">
                <i class="fa fa-shopping-cart"></i> В корзину
            </a>
        </p>
    </div>
</div>

Likhtarovich_90311/Views/Animal/_ListPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

@model ListViewModel<Animal>
@foreach (var item in Model)
{
    <partial name="_ListItemPartial" model="@item" />
}